export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const UPLOAD_CREATE="UPLOAD_CREATE";
export const UPLOAD_UPDATE="UPLOAD_UPDATE";
export const UPLOAD_DELETE="UPLOAD_DELETE";
export const UPLOAD_CREATE_FAILL="UPLOAD_CREATE_FAILL";
export const UPLOAD_CREATE_SUCCESS="UPLOAD_CREATE_SUCCESS";
